[[headers]]
  for = "/api/orders"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
[functions]
  included_files = ["node_modules/@prisma/**/*"]

[functions.timeout]
external_node_modules = ["@prisma/client"]

[build]
  command = "npm run build"
  publish = ".next"