[[headers]]
  for = "/api/orders"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
[functions]
  # Increase the function timeout to 30 seconds (or more)
  max_duration = 60